// Copyright 2026 OWASP Coraza
// Author: Juan Pablo Tosso <pablo@owasp.org>
// SPDX-License-Identifier: Apache-2.0

package knowledge

// allTransformations contains all known SecLang transformation functions.
// Transformations are applied to variable values before operator matching.
// They create a copy — the original value is not modified.
var allTransformations = []Item{
	{
		Name:        "none",
		Summary:     "Clear all inherited transformations from SecDefaultAction",
		Syntax:      "t:none",
		Example:     `t:none,t:lowercase`,
		Description: "**none** removes all transformations inherited from `SecDefaultAction`. Always use `t:none` first when you want to control the full transformation pipeline.",
	},
	{
		Name:        "lowercase",
		Summary:     "Convert all characters to lowercase",
		Syntax:      "t:lowercase",
		Example:     `SecRule ARGS "@rx select" "id:1,phase:2,deny,t:lowercase"`,
		Description: "**lowercase** converts the value to lowercase using the current locale. The most commonly used transformation for case-insensitive matching.",
	},
	{
		Name:        "uppercase",
		Summary:     "Convert all characters to uppercase",
		Syntax:      "t:uppercase",
		Example:     `SecRule ARGS "@rx SELECT" "id:2,phase:2,deny,t:uppercase"`,
		Description: "**uppercase** converts the value to uppercase using the current locale.",
	},
	{
		Name:        "urlDecode",
		Summary:     "Decode URL-encoded characters (%XX sequences)",
		Syntax:      "t:urlDecode",
		Example:     `SecRule ARGS "@rx <script" "id:3,phase:2,deny,t:urlDecode,t:lowercase"`,
		Description: "**urlDecode** decodes standard URL-encoded characters (`%XX` sequences). Apply before matching to detect encoded attacks.",
	},
	{
		Name:        "urlDecodeUni",
		Summary:     "URL decode including Microsoft %uXXXX Unicode encoding",
		Syntax:      "t:urlDecodeUni",
		Example:     `SecRule ARGS "@rx script" "id:4,phase:2,deny,t:urlDecodeUni,t:lowercase"`,
		Description: "**urlDecodeUni** decodes both standard `%XX` URL encoding and Microsoft's `%uXXXX` Unicode encoding. More thorough than `urlDecode` for IIS environments.",
	},
	{
		Name:        "urlEncode",
		Summary:     "Encode special characters using URL encoding",
		Syntax:      "t:urlEncode",
		Example:     `SecRule TX:data "@rx %3C" "id:5,phase:2,deny,t:urlEncode"`,
		Description: "**urlEncode** encodes characters using `%XX` URL encoding. Rarely used in matching — mainly for data manipulation.",
	},
	{
		Name:        "base64Decode",
		Summary:     "Decode a Base64-encoded string",
		Syntax:      "t:base64Decode",
		Example:     `SecRule ARGS "@rx <script" "id:6,phase:2,deny,t:base64Decode,t:lowercase"`,
		Description: "**base64Decode** decodes Base64-encoded data. Strict decoding — invalid characters cause an error.",
	},
	{
		Name:        "base64DecodeExt",
		Summary:     "Decode Base64 while ignoring invalid characters",
		Syntax:      "t:base64DecodeExt",
		Example:     `SecRule ARGS "@rx eval" "id:7,phase:2,deny,t:base64DecodeExt"`,
		Description: "**base64DecodeExt** decodes Base64 data but ignores invalid (non-Base64) characters. More forgiving than `base64Decode`.",
	},
	{
		Name:        "base64Encode",
		Summary:     "Encode data using Base64",
		Syntax:      "t:base64Encode",
		Example:     `SecRule TX:sensitive "@rx cGFzc3dvcmQ=" "id:8,phase:2,deny,t:base64Encode"`,
		Description: "**base64Encode** encodes the value using Base64 encoding.",
	},
	{
		Name:        "htmlEntityDecode",
		Summary:     "Decode HTML entities (both numeric and named)",
		Syntax:      "t:htmlEntityDecode",
		Example:     `SecRule ARGS "@rx <script" "id:9,phase:2,deny,t:htmlEntityDecode,t:lowercase"`,
		Description: "**htmlEntityDecode** decodes HTML character entities, both named (`&lt;`, `&amp;`) and numeric (`&#60;`, `&#x3C;`). Essential for detecting XSS through HTML encoding.",
	},
	{
		Name:        "jsDecode",
		Summary:     "Decode JavaScript escape sequences",
		Syntax:      "t:jsDecode",
		Example:     `SecRule ARGS "@rx eval" "id:10,phase:2,deny,t:jsDecode"`,
		Description: "**jsDecode** decodes JavaScript string escape sequences: `\\xHH`, `\\uHHHH`, `\\n`, `\\t`, `\\\\`, etc.",
	},
	{
		Name:        "cssDecode",
		Summary:     "Decode CSS 2.x escape sequences",
		Syntax:      "t:cssDecode",
		Example:     `SecRule ARGS "@rx expression" "id:11,phase:2,deny,t:cssDecode,t:lowercase"`,
		Description: "**cssDecode** decodes CSS escape sequences used in stylesheets (e.g. `\\000041` for `A`).",
	},
	{
		Name:        "hexDecode",
		Summary:     "Decode hexadecimal-encoded data",
		Syntax:      "t:hexDecode",
		Example:     `SecRule ARGS "@rx deadbeef" "id:12,phase:2,deny,t:hexDecode"`,
		Description: "**hexDecode** decodes data where bytes are represented as two-character hex sequences.",
	},
	{
		Name:        "hexEncode",
		Summary:     "Encode bytes as hexadecimal pairs",
		Syntax:      "t:hexEncode",
		Example:     `SecRule TX:data "@rx 3c73637" "id:13,phase:2,deny,t:hexEncode"`,
		Description: "**hexEncode** converts each byte to its two-character lowercase hexadecimal representation.",
	},
	{
		Name:        "sqlHexDecode",
		Summary:     "Decode SQL hex notation (0x414243 format)",
		Syntax:      "t:sqlHexDecode",
		Example:     `SecRule ARGS "@rx select" "id:14,phase:2,deny,t:sqlHexDecode,t:lowercase"`,
		Description: "**sqlHexDecode** decodes SQL hex-encoded strings in `0xHH...` format used in SQL injection attacks.",
	},
	{
		Name:        "escapeSeqDecode",
		Summary:     "Decode ANSI C escape sequences",
		Syntax:      "t:escapeSeqDecode",
		Example:     `SecRule ARGS "@rx exec" "id:15,phase:2,deny,t:escapeSeqDecode"`,
		Description: "**escapeSeqDecode** decodes C-style escape sequences: `\\a`, `\\b`, `\\f`, `\\n`, `\\r`, `\\t`, `\\v`, `\\\\`, `\\'`, `\\\"`, `\\ooo` (octal), `\\xHH` (hex).",
	},
	{
		Name:        "utf8toUnicode",
		Summary:     "Convert UTF-8 sequences to Unicode escape notation",
		Syntax:      "t:utf8toUnicode",
		Example:     `SecRule ARGS "@rx script" "id:16,phase:2,deny,t:utf8toUnicode,t:urlDecodeUni"`,
		Description: "**utf8toUnicode** converts UTF-8 multi-byte sequences into their `%uXXXX` Unicode code point representation.",
	},
	{
		Name:        "compressWhitespace",
		Summary:     "Replace whitespace sequences with a single space",
		Syntax:      "t:compressWhitespace",
		Example:     `SecRule ARGS "@rx union select" "id:17,phase:2,deny,t:compressWhitespace,t:lowercase"`,
		Description: "**compressWhitespace** replaces sequences of whitespace characters (space, tab, newline, etc.) with a single space. Helps detect SQL injection with extra whitespace.",
	},
	{
		Name:        "removeWhitespace",
		Summary:     "Remove all whitespace characters",
		Syntax:      "t:removeWhitespace",
		Example:     `SecRule ARGS "@rx unionselect" "id:18,phase:2,deny,t:removeWhitespace,t:lowercase"`,
		Description: "**removeWhitespace** strips all whitespace characters from the value. Useful for detecting SQL injection where attackers use whitespace to evade detection.",
	},
	{
		Name:        "removeNulls",
		Summary:     "Remove null bytes from the value",
		Syntax:      "t:removeNulls",
		Example:     `SecRule ARGS "@rx <script" "id:19,phase:2,deny,t:removeNulls"`,
		Description: "**removeNulls** strips NUL (`\\x00`) bytes from the value. NUL bytes can be used to bypass string matching.",
	},
	{
		Name:        "replaceNulls",
		Summary:     "Replace null bytes with spaces",
		Syntax:      "t:replaceNulls",
		Example:     `SecRule ARGS "@rx select" "id:20,phase:2,deny,t:replaceNulls,t:lowercase"`,
		Description: "**replaceNulls** replaces NUL (`\\x00`) bytes with spaces, preserving the string length.",
	},
	{
		Name:        "removeComments",
		Summary:     "Remove SQL/C-style comment sequences",
		Syntax:      "t:removeComments",
		Example:     `SecRule ARGS "@rx union.*select" "id:21,phase:2,deny,t:removeComments,t:lowercase"`,
		Description: "**removeComments** removes SQL comment sequences (`/*...*/` and `--`). Helps detect SQL injection that uses comments to break up keywords.",
	},
	{
		Name:        "replaceComments",
		Summary:     "Replace SQL/C-style comments with a single space",
		Syntax:      "t:replaceComments",
		Example:     `SecRule ARGS "@rx union select" "id:22,phase:2,deny,t:replaceComments,t:lowercase"`,
		Description: "**replaceComments** replaces comment sequences with a single space rather than removing them entirely, preserving word boundaries.",
	},
	{
		Name:        "removeCommentsChar",
		Summary:     "Remove comment-marking characters",
		Syntax:      "t:removeCommentsChar",
		Example:     `SecRule ARGS "@rx union" "id:23,phase:2,deny,t:removeCommentsChar,t:lowercase"`,
		Description: "**removeCommentsChar** removes characters used to start comments: `/*`, `*/`, `--`, `#`.",
	},
	{
		Name:        "trim",
		Summary:     "Remove leading and trailing whitespace",
		Syntax:      "t:trim",
		Example:     `SecRule ARGS:username "@streq admin" "id:24,phase:2,deny,t:trim,t:lowercase"`,
		Description: "**trim** removes whitespace from both the start and end of the value.",
	},
	{
		Name:        "trimLeft",
		Summary:     "Remove leading whitespace",
		Syntax:      "t:trimLeft",
		Example:     `SecRule ARGS "@streq  value" "id:25,phase:2,deny,t:trimLeft"`,
		Description: "**trimLeft** removes whitespace from the beginning of the value.",
	},
	{
		Name:        "trimRight",
		Summary:     "Remove trailing whitespace",
		Syntax:      "t:trimRight",
		Example:     `SecRule ARGS "@streq value " "id:26,phase:2,deny,t:trimRight"`,
		Description: "**trimRight** removes whitespace from the end of the value.",
	},
	{
		Name:        "normalisePath",
		Aliases:     []string{"normalizePath"},
		Summary:     "Resolve path traversal sequences (. and ..)",
		Syntax:      "t:normalisePath",
		Example:     `SecRule ARGS "@rx /etc/passwd" "id:27,phase:2,deny,t:normalisePath"`,
		Description: "**normalisePath** removes directory traversal sequences (`.` and `..`) and multiple slashes from paths. Also accepted as `normalizePath`.",
	},
	{
		Name:        "normalizePathWin",
		Aliases:     []string{"normalisePathWin"},
		Summary:     "Resolve Windows-style path traversal sequences",
		Syntax:      "t:normalizePathWin",
		Example:     `SecRule ARGS "@rx /etc/passwd" "id:28,phase:2,deny,t:normalizePathWin"`,
		Description: "**normalizePathWin** like `normalisePath` but also converts backslashes to forward slashes first, handling Windows path syntax.",
	},
	{
		Name:        "length",
		Summary:     "Replace the value with its byte length as a decimal string",
		Syntax:      "t:length",
		Example:     `SecRule ARGS "@gt 1000" "id:29,phase:2,deny,t:length"`,
		Description: "**length** replaces the value with its length in bytes. Use with numeric operators to impose length limits.",
	},
	{
		Name:        "md5",
		Summary:     "Replace the value with its MD5 hash (hex-encoded)",
		Syntax:      "t:md5",
		Example:     `SecRule TX:token "@streq d41d8cd98f00b204e9800998ecf8427e" "id:30,phase:2,deny,t:md5"`,
		Description: "**md5** computes the MD5 hash of the value and returns it as a lowercase hex string.",
	},
	{
		Name:        "sha1",
		Summary:     "Replace the value with its SHA-1 hash (hex-encoded)",
		Syntax:      "t:sha1",
		Example:     `SecRule TX:token "@streq da39a3ee5e6b4b0d3255bfef95601890afd80709" "id:31,phase:2,deny,t:sha1"`,
		Description: "**sha1** computes the SHA-1 hash of the value and returns it as a lowercase hex string.",
	},
	{
		Name:        "cmdLine",
		Summary:     "Normalize a command-line string to defeat evasion",
		Syntax:      "t:cmdLine",
		Example:     `SecRule ARGS "@rx cmd.exe" "id:32,phase:2,deny,t:cmdLine,t:lowercase"`,
		Description: "**cmdLine** manipulates command-line strings to defeat common evasion techniques: removes carets, redundant whitespace, and normalizes common shell metacharacters.",
	},
}
