// Copyright 2026 OWASP Coraza
// Author: Juan Pablo Tosso <pablo@owasp.org>
// SPDX-License-Identifier: Apache-2.0

package knowledge

// allVariables contains all known SecLang collection variables with full documentation.
var allVariables = []Item{
	// Request Arguments
	{
		Name:        "ARGS",
		Summary:     "All request arguments (GET query string + POST body combined)",
		Syntax:      "ARGS[:key]",
		Example:     `SecRule ARGS "@rx <script" "id:1,phase:2,deny"`,
		Description: "**ARGS** contains all request parameters regardless of source. Use `:key` to target a specific parameter name. Supports regex key syntax: `ARGS:/^param_.*/`.",
	},
	{
		Name:        "ARGS_GET",
		Summary:     "Query string parameters only",
		Syntax:      "ARGS_GET[:key]",
		Example:     `SecRule ARGS_GET:id "@rx [^0-9]" "id:2,phase:1,deny"`,
		Description: "**ARGS_GET** contains only GET (query string) parameters. Use when you need to distinguish between GET and POST parameters.",
	},
	{
		Name:        "ARGS_POST",
		Summary:     "POST body parameters only",
		Syntax:      "ARGS_POST[:key]",
		Example:     `SecRule ARGS_POST:username "@rx admin" "id:3,phase:2,deny"`,
		Description: "**ARGS_POST** contains only POST body parameters. Requires `SecRequestBodyAccess On`.",
	},
	{
		Name:        "ARGS_NAMES",
		Summary:     "Names of all request arguments (GET + POST)",
		Syntax:      "ARGS_NAMES",
		Example:     `SecRule ARGS_NAMES "@rx __proto__" "id:4,phase:2,deny"`,
		Description: "**ARGS_NAMES** is a collection of all parameter *names* (not values). Useful for detecting prototype pollution or suspicious parameter names.",
	},
	{
		Name:        "ARGS_GET_NAMES",
		Summary:     "Names of GET query string parameters",
		Syntax:      "ARGS_GET_NAMES",
		Example:     `SecRule ARGS_GET_NAMES "@rx ^debug" "id:5,phase:1,deny"`,
		Description: "**ARGS_GET_NAMES** contains only the names of query string parameters.",
	},
	{
		Name:        "ARGS_POST_NAMES",
		Summary:     "Names of POST body parameters",
		Syntax:      "ARGS_POST_NAMES",
		Example:     `SecRule ARGS_POST_NAMES "@rx ^file" "id:6,phase:2,deny"`,
		Description: "**ARGS_POST_NAMES** contains only the names of POST body parameters.",
	},
	{
		Name:        "ARGS_COMBINED_SIZE",
		Summary:     "Total byte size of all request arguments",
		Syntax:      "ARGS_COMBINED_SIZE",
		Example:     `SecRule ARGS_COMBINED_SIZE "@gt 10000" "id:7,phase:2,deny"`,
		Description: "**ARGS_COMBINED_SIZE** is the total length in bytes of all argument names and values combined. Use with numeric operators to enforce size limits.",
	},
	// Request Line
	{
		Name:        "REQUEST_LINE",
		Summary:     "Complete HTTP request line (method, URI, protocol)",
		Syntax:      "REQUEST_LINE",
		Example:     `SecRule REQUEST_LINE "@rx HTTP/0\\.9" "id:10,phase:1,deny"`,
		Description: "**REQUEST_LINE** contains the full first line of the HTTP request, e.g. `GET /index.php?id=1 HTTP/1.1`.",
	},
	{
		Name:        "REQUEST_METHOD",
		Summary:     "HTTP request method (GET, POST, PUT, etc.)",
		Syntax:      "REQUEST_METHOD",
		Example:     `SecRule REQUEST_METHOD "@pm CONNECT TRACE" "id:11,phase:1,deny"`,
		Description: "**REQUEST_METHOD** contains the HTTP method in uppercase.",
	},
	{
		Name:        "REQUEST_PROTOCOL",
		Summary:     "HTTP protocol version",
		Syntax:      "REQUEST_PROTOCOL",
		Example:     `SecRule REQUEST_PROTOCOL "!@rx ^HTTP/(1\\.0|1\\.1|2\\.0|3\\.0)$" "id:12,phase:1,deny"`,
		Description: "**REQUEST_PROTOCOL** contains the HTTP protocol version string, e.g. `HTTP/1.1`.",
	},
	{
		Name:        "REQUEST_URI",
		Summary:     "Request URI path and query string (without domain)",
		Syntax:      "REQUEST_URI",
		Example:     `SecRule REQUEST_URI "@rx /admin" "id:13,phase:1,deny"`,
		Description: "**REQUEST_URI** contains the URI path and query string as sent by the client, without scheme or host.",
	},
	{
		Name:        "REQUEST_URI_RAW",
		Summary:     "Full request URI including domain if present",
		Syntax:      "REQUEST_URI_RAW",
		Example:     `SecRule REQUEST_URI_RAW "@rx example\\.com" "id:14,phase:1,deny"`,
		Description: "**REQUEST_URI_RAW** is like `REQUEST_URI` but includes the full absolute URI if the client sent one (e.g. in proxy requests).",
	},
	{
		Name:        "REQUEST_FILENAME",
		Summary:     "Relative path portion of the request URI",
		Syntax:      "REQUEST_FILENAME",
		Example:     `SecRule REQUEST_FILENAME "@rx \\.php$" "id:15,phase:1,pass"`,
		Description: "**REQUEST_FILENAME** contains the path component of the request URI, without the query string.",
	},
	{
		Name:        "REQUEST_BASENAME",
		Summary:     "Filename component of the request URI path",
		Syntax:      "REQUEST_BASENAME",
		Example:     `SecRule REQUEST_BASENAME "@rx ^eval\\.php$" "id:16,phase:1,deny"`,
		Description: "**REQUEST_BASENAME** contains just the filename part (last path segment) of `REQUEST_FILENAME`.",
	},
	{
		Name:        "QUERY_STRING",
		Summary:     "Raw query string from the request URI",
		Syntax:      "QUERY_STRING",
		Example:     `SecRule QUERY_STRING "@rx union.*select" "id:17,phase:1,deny,t:lowercase"`,
		Description: "**QUERY_STRING** contains the raw (undecoded) query string, exactly as received. Use transformations to normalize before matching.",
	},
	// Request Headers
	{
		Name:        "REQUEST_HEADERS",
		Summary:     "All HTTP request headers as a collection",
		Syntax:      "REQUEST_HEADERS[:header-name]",
		Example:     `SecRule REQUEST_HEADERS:User-Agent "@rx sqlmap" "id:20,phase:1,deny"`,
		Description: "**REQUEST_HEADERS** contains all HTTP request headers. Use `:header-name` (case-insensitive) to target a specific header.",
	},
	{
		Name:        "REQUEST_HEADERS_NAMES",
		Summary:     "Names of all HTTP request headers",
		Syntax:      "REQUEST_HEADERS_NAMES",
		Example:     `SecRule REQUEST_HEADERS_NAMES "@rx ^x-forwarded" "id:21,phase:1,pass,log"`,
		Description: "**REQUEST_HEADERS_NAMES** is a collection of all request header names.",
	},
	{
		Name:        "REQUEST_COOKIES",
		Summary:     "All request cookies as a collection",
		Syntax:      "REQUEST_COOKIES[:cookie-name]",
		Example:     `SecRule REQUEST_COOKIES:session "@rx ^[a-f0-9]{32}$" "id:22,phase:1,pass"`,
		Description: "**REQUEST_COOKIES** contains all cookies sent in the request. Use `:cookie-name` to target a specific cookie.",
	},
	{
		Name:        "REQUEST_COOKIES_NAMES",
		Summary:     "Names of all request cookies",
		Syntax:      "REQUEST_COOKIES_NAMES",
		Example:     `SecRule REQUEST_COOKIES_NAMES "@rx ^__utm" "id:23,phase:1,pass"`,
		Description: "**REQUEST_COOKIES_NAMES** is a collection of all cookie names in the request.",
	},
	// Request Body
	{
		Name:        "REQUEST_BODY",
		Summary:     "Raw request body content",
		Syntax:      "REQUEST_BODY",
		Example:     `SecRule REQUEST_BODY "@rx union.*select" "id:30,phase:2,deny,t:lowercase"`,
		Description: "**REQUEST_BODY** contains the raw request body as a string. Requires `SecRequestBodyAccess On`. For parsed arguments, prefer `ARGS_POST`.",
	},
	{
		Name:        "REQUEST_BODY_LENGTH",
		Summary:     "Size of the request body in bytes",
		Syntax:      "REQUEST_BODY_LENGTH",
		Example:     `SecRule REQUEST_BODY_LENGTH "@gt 1048576" "id:31,phase:2,deny"`,
		Description: "**REQUEST_BODY_LENGTH** contains the byte length of the request body.",
	},
	// File Uploads
	{
		Name:        "FILES",
		Summary:     "Names of uploaded files in multipart requests",
		Syntax:      "FILES",
		Example:     `SecRule FILES "@rx \\.php$" "id:40,phase:2,deny"`,
		Description: "**FILES** is a collection of uploaded file names. Available only for `multipart/form-data` requests.",
	},
	{
		Name:        "FILES_NAMES",
		Summary:     "Form field names for file upload fields",
		Syntax:      "FILES_NAMES",
		Example:     `SecRule FILES_NAMES "@rx upload" "id:41,phase:2,pass,log"`,
		Description: "**FILES_NAMES** contains the form field names (not file names) of file upload inputs.",
	},
	{
		Name:        "FILES_SIZES",
		Summary:     "Sizes of individual uploaded files",
		Syntax:      "FILES_SIZES",
		Example:     `SecRule FILES_SIZES "@gt 10485760" "id:42,phase:2,deny"`,
		Description: "**FILES_SIZES** is a collection of the sizes (bytes) of each uploaded file.",
	},
	{
		Name:        "FILES_TMPNAMES",
		Summary:     "Temporary file paths for uploaded files",
		Syntax:      "FILES_TMPNAMES",
		Example:     `SecRule FILES_TMPNAMES "@inspectFile /usr/local/bin/avcheck" "id:43,phase:2,deny"`,
		Description: "**FILES_TMPNAMES** contains the paths of temporary files created for uploaded content.",
	},
	{
		Name:        "FILES_TMP_CONTENT",
		Summary:     "Content of uploaded files",
		Syntax:      "FILES_TMP_CONTENT",
		Example:     `SecRule FILES_TMP_CONTENT "@rx <\\?php" "id:44,phase:2,deny"`,
		Description: "**FILES_TMP_CONTENT** contains the raw content of uploaded files for inspection.",
	},
	{
		Name:        "FILES_COMBINED_SIZE",
		Summary:     "Total byte size of all uploaded files",
		Syntax:      "FILES_COMBINED_SIZE",
		Example:     `SecRule FILES_COMBINED_SIZE "@gt 52428800" "id:45,phase:2,deny"`,
		Description: "**FILES_COMBINED_SIZE** is the total size of all files uploaded in this request.",
	},
	// Response Variables
	{
		Name:        "RESPONSE_BODY",
		Summary:     "Response body content (requires SecResponseBodyAccess On)",
		Syntax:      "RESPONSE_BODY",
		Example:     `SecRule RESPONSE_BODY "@rx credit.card" "id:50,phase:4,deny"`,
		Description: "**RESPONSE_BODY** contains the buffered response body. Requires `SecResponseBodyAccess On` and a matching MIME type in `SecResponseBodyMimeType`.",
	},
	{
		Name:        "RESPONSE_HEADERS",
		Summary:     "All HTTP response headers as a collection",
		Syntax:      "RESPONSE_HEADERS[:header-name]",
		Example:     `SecRule RESPONSE_HEADERS:Server "@rx Apache/1" "id:51,phase:3,pass,log"`,
		Description: "**RESPONSE_HEADERS** contains all response headers. Use `:header-name` to target a specific header.",
	},
	{
		Name:        "RESPONSE_HEADERS_NAMES",
		Summary:     "Names of all HTTP response headers",
		Syntax:      "RESPONSE_HEADERS_NAMES",
		Example:     `SecRule RESPONSE_HEADERS_NAMES "@rx x-powered-by" "id:52,phase:3,pass,log"`,
		Description: "**RESPONSE_HEADERS_NAMES** is a collection of all response header names.",
	},
	{
		Name:        "RESPONSE_CONTENT_LENGTH",
		Summary:     "Response Content-Length header value",
		Syntax:      "RESPONSE_CONTENT_LENGTH",
		Example:     `SecRule RESPONSE_CONTENT_LENGTH "@gt 10485760" "id:53,phase:3,deny"`,
		Description: "**RESPONSE_CONTENT_LENGTH** contains the value of the `Content-Length` response header as a string.",
	},
	{
		Name:        "RESPONSE_CONTENT_TYPE",
		Summary:     "Response Content-Type header value",
		Syntax:      "RESPONSE_CONTENT_TYPE",
		Example:     `SecRule RESPONSE_CONTENT_TYPE "@rx text/html" "id:54,phase:3,pass"`,
		Description: "**RESPONSE_CONTENT_TYPE** contains the value of the `Content-Type` response header.",
	},
	{
		Name:        "RESPONSE_STATUS",
		Summary:     "HTTP response status code",
		Syntax:      "RESPONSE_STATUS",
		Example:     `SecRule RESPONSE_STATUS "@rx ^5" "id:55,phase:3,pass,log"`,
		Description: "**RESPONSE_STATUS** contains the HTTP response status code as a string (e.g. `200`, `404`).",
	},
	{
		Name:        "RESPONSE_PROTOCOL",
		Summary:     "HTTP response protocol version",
		Syntax:      "RESPONSE_PROTOCOL",
		Example:     `SecRule RESPONSE_PROTOCOL "@streq HTTP/1.0" "id:56,phase:3,pass"`,
		Description: "**RESPONSE_PROTOCOL** contains the HTTP protocol version from the response status line.",
	},
	{
		Name:        "STATUS_LINE",
		Summary:     "Complete HTTP response status line",
		Syntax:      "STATUS_LINE",
		Example:     `SecRule STATUS_LINE "@rx 5[0-9]{2}" "id:57,phase:3,pass,log"`,
		Description: "**STATUS_LINE** contains the full status line, e.g. `HTTP/1.1 200 OK`.",
	},
	// Server & Client
	{
		Name:        "REMOTE_ADDR",
		Summary:     "Client IP address",
		Syntax:      "REMOTE_ADDR",
		Example:     `SecRule REMOTE_ADDR "@ipMatch 192.168.0.0/16" "id:60,phase:1,allow"`,
		Description: "**REMOTE_ADDR** contains the IP address of the connecting client.",
	},
	{
		Name:        "REMOTE_HOST",
		Summary:     "Client hostname (if reverse DNS is available)",
		Syntax:      "REMOTE_HOST",
		Example:     `SecRule REMOTE_HOST "@rx \\.tor2web\\.org$" "id:61,phase:1,deny"`,
		Description: "**REMOTE_HOST** contains the resolved hostname of the client. Usually same as `REMOTE_ADDR` unless reverse DNS is performed.",
	},
	{
		Name:        "REMOTE_PORT",
		Summary:     "Client source TCP port",
		Syntax:      "REMOTE_PORT",
		Example:     `SecRule REMOTE_PORT "@lt 1024" "id:62,phase:1,pass,log"`,
		Description: "**REMOTE_PORT** contains the TCP source port number of the client connection.",
	},
	{
		Name:        "REMOTE_USER",
		Summary:     "Authenticated username",
		Syntax:      "REMOTE_USER",
		Example:     `SecRule REMOTE_USER "@streq admin" "id:63,phase:1,pass,log"`,
		Description: "**REMOTE_USER** contains the username from HTTP authentication, if any.",
	},
	{
		Name:        "SERVER_ADDR",
		Summary:     "Server IP address",
		Syntax:      "SERVER_ADDR",
		Example:     `SecRule SERVER_ADDR "@ipMatch 10.0.0.0/8" "id:64,phase:1,pass"`,
		Description: "**SERVER_ADDR** contains the IP address of the server that received the request.",
	},
	{
		Name:        "SERVER_NAME",
		Summary:     "Server hostname from the Host header",
		Syntax:      "SERVER_NAME",
		Example:     `SecRule SERVER_NAME "@streq api.example.com" "id:65,phase:1,pass"`,
		Description: "**SERVER_NAME** contains the virtual host name from the `Host` header.",
	},
	{
		Name:        "SERVER_PORT",
		Summary:     "Server listening TCP port",
		Syntax:      "SERVER_PORT",
		Example:     `SecRule SERVER_PORT "@eq 8080" "id:66,phase:1,pass,log"`,
		Description: "**SERVER_PORT** contains the TCP port the server is listening on.",
	},
	{
		Name:        "AUTH_TYPE",
		Summary:     "HTTP authentication method in use",
		Syntax:      "AUTH_TYPE",
		Example:     `SecRule AUTH_TYPE "@streq Basic" "id:67,phase:1,pass,log"`,
		Description: "**AUTH_TYPE** contains the HTTP authentication scheme (e.g. `Basic`, `Digest`, `Bearer`).",
	},
	// Error & Processing
	{
		Name:        "REQBODY_ERROR",
		Summary:     "Non-zero when request body parsing failed",
		Syntax:      "REQBODY_ERROR",
		Example:     `SecRule REQBODY_ERROR "!@eq 0" "id:70,phase:2,deny,msg:'Request body parsing error'"`,
		Description: "**REQBODY_ERROR** is set to a non-zero value when the request body processor encounters a parse error.",
	},
	{
		Name:        "REQBODY_ERROR_MSG",
		Summary:     "Error message from request body parser",
		Syntax:      "REQBODY_ERROR_MSG",
		Example:     `SecRule REQBODY_ERROR "!@eq 0" "id:71,phase:2,deny,logdata:'%{REQBODY_ERROR_MSG}'"`,
		Description: "**REQBODY_ERROR_MSG** contains the human-readable error message when `REQBODY_ERROR` is non-zero.",
	},
	{
		Name:        "REQBODY_PROCESSOR",
		Summary:     "Active request body processor type",
		Syntax:      "REQBODY_PROCESSOR",
		Example:     `SecRule REQBODY_PROCESSOR "@streq JSON" "id:72,phase:2,pass,log"`,
		Description: "**REQBODY_PROCESSOR** indicates which parser processed the request body: `URLENCODED`, `MULTIPART`, `JSON`, `XML`, or empty if none.",
	},
	{
		Name:        "INBOUND_DATA_ERROR",
		Summary:     "Set when request body exceeded configured size limits",
		Syntax:      "INBOUND_DATA_ERROR",
		Example:     `SecRule INBOUND_DATA_ERROR "!@eq 0" "id:73,phase:2,deny"`,
		Description: "**INBOUND_DATA_ERROR** is set when the request body exceeds `SecRequestBodyLimit`.",
	},
	{
		Name:        "OUTBOUND_DATA_ERROR",
		Summary:     "Set when response body exceeded configured size limits",
		Syntax:      "OUTBOUND_DATA_ERROR",
		Example:     `SecRule OUTBOUND_DATA_ERROR "!@eq 0" "id:74,phase:4,pass,log"`,
		Description: "**OUTBOUND_DATA_ERROR** is set when the response body exceeds `SecResponseBodyLimit`.",
	},
	// Multipart
	{
		Name:        "MULTIPART_STRICT_ERROR",
		Summary:     "Set when multipart body fails strict validation",
		Syntax:      "MULTIPART_STRICT_ERROR",
		Example:     `SecRule MULTIPART_STRICT_ERROR "!@eq 0" "id:80,phase:2,deny"`,
		Description: "**MULTIPART_STRICT_ERROR** is set to non-zero when the multipart parser detects violations of the RFC specification.",
	},
	{
		Name:        "MULTIPART_UNMATCHED_BOUNDARY",
		Summary:     "Set when multipart boundary is not found",
		Syntax:      "MULTIPART_UNMATCHED_BOUNDARY",
		Example:     `SecRule MULTIPART_UNMATCHED_BOUNDARY "!@eq 0" "id:81,phase:2,deny"`,
		Description: "**MULTIPART_UNMATCHED_BOUNDARY** is set when the Content-Type boundary is not found in the request body.",
	},
	// Time & Performance
	{
		Name:        "TIME",
		Summary:     "Current time as formatted string",
		Syntax:      "TIME",
		Example:     `SecRule TIME "@rx ^[0-1][0-9]" "id:90,phase:1,pass,log,msg:'Nighttime access'"`,
		Description: "**TIME** contains the current time in the format `HHMMSS`.",
	},
	{
		Name:        "TIME_EPOCH",
		Summary:     "Current Unix timestamp (seconds since 1970)",
		Syntax:      "TIME_EPOCH",
		Example:     `SecAction "id:91,phase:1,pass,setvar:tx.timestamp=%{TIME_EPOCH}"`,
		Description: "**TIME_EPOCH** contains the number of seconds elapsed since the Unix epoch.",
	},
	{
		Name:        "DURATION",
		Summary:     "Time elapsed since the start of the transaction (milliseconds)",
		Syntax:      "DURATION",
		Example:     `SecRule DURATION "@gt 5000" "id:92,phase:5,pass,log,msg:'Slow transaction'"`,
		Description: "**DURATION** contains the number of milliseconds elapsed since the WAF began processing this transaction.",
	},
	// Matching
	{
		Name:        "MATCHED_VAR",
		Summary:     "Value of the most recently matched variable",
		Syntax:      "MATCHED_VAR",
		Example:     `SecRule ARGS "@rx union" "id:100,phase:2,deny,logdata:'Matched: %{MATCHED_VAR}'"`,
		Description: "**MATCHED_VAR** contains the value of the variable that last triggered a rule match. Useful in `logdata` and `msg` for recording what was matched.",
	},
	{
		Name:        "MATCHED_VARS",
		Summary:     "All variable values matched in the current rule evaluation",
		Syntax:      "MATCHED_VARS",
		Example:     `SecRule MATCHED_VARS "@rx <script" "id:101,phase:2,deny"`,
		Description: "**MATCHED_VARS** is a collection of all values that matched during the current rule evaluation (when inspecting multiple variables).",
	},
	{
		Name:        "MATCHED_VAR_NAME",
		Summary:     "Name of the most recently matched variable",
		Syntax:      "MATCHED_VAR_NAME",
		Example:     `SecRule ARGS "@rx union" "id:102,phase:2,deny,logdata:'In: %{MATCHED_VAR_NAME}'"`,
		Description: "**MATCHED_VAR_NAME** contains the name (including collection key) of the variable that last triggered a match.",
	},
	{
		Name:        "MATCHED_VARS_NAMES",
		Summary:     "Names of all variables matched in the current rule evaluation",
		Syntax:      "MATCHED_VARS_NAMES",
		Example:     `SecRule MATCHED_VARS_NAMES "@rx ARGS:id" "id:103,phase:2,deny"`,
		Description: "**MATCHED_VARS_NAMES** is a collection of all matched variable names during the current rule evaluation.",
	},
	{
		Name:        "HIGHEST_SEVERITY",
		Summary:     "Highest severity score from all matched rules in the transaction",
		Syntax:      "HIGHEST_SEVERITY",
		Example:     `SecRule HIGHEST_SEVERITY "@le 4" "id:104,phase:5,pass,log"`,
		Description: "**HIGHEST_SEVERITY** contains the numeric severity (0=EMERGENCY, 7=DEBUG) of the most severe rule match so far. Lower numbers are more severe.",
	},
	// Persistent Collections
	{
		Name:        "TX",
		Summary:     "Per-transaction variables (local to this request)",
		Syntax:      "TX[:key]",
		Example:     `SecAction "id:110,phase:1,pass,setvar:TX.anomaly_score=0"`,
		Description: "**TX** is the transaction collection. Variables set here exist only for the duration of the current transaction. TX:0–TX:9 are capture group variables set by the `capture` action.",
	},
	{
		Name:        "IP",
		Summary:     "Persistent per-IP address collection",
		Syntax:      "IP[:key]",
		Example:     `SecAction "id:111,phase:1,pass,initcol:IP=%{REMOTE_ADDR}"`,
		Description: "**IP** is a persistent collection keyed by IP address. Data survives across requests from the same client IP. Requires `initcol:IP=...` to initialize.",
	},
	{
		Name:        "SESSION",
		Summary:     "Persistent per-session collection",
		Syntax:      "SESSION[:key]",
		Example:     `SecAction "id:112,phase:1,pass,setsid:%{REQUEST_COOKIES:session}"`,
		Description: "**SESSION** is a persistent collection keyed by session token. Data survives across requests in the same session. Initialize with `setsid`.",
	},
	{
		Name:        "GEO",
		Summary:     "Geolocation data populated by @geoLookup operator",
		Syntax:      "GEO[:field]",
		Example:     `SecRule REMOTE_ADDR "@geoLookup" "id:113,phase:1,pass"` + "\n" + `SecRule GEO:COUNTRY_CODE "@pm CN RU" "id:114,phase:1,deny"`,
		Description: "**GEO** contains geolocation data after a `@geoLookup` operator match. Fields include `COUNTRY_CODE`, `COUNTRY_NAME`, `CITY`, `LATITUDE`, `LONGITUDE`.",
	},
	{
		Name:        "XML",
		Summary:     "XML body parsed data accessible via XPath",
		Syntax:      "XML[xpath-expression]",
		Example:     `SecRule XML://*/@href "@rx javascript:" "id:120,phase:2,deny"`,
		Description: "**XML** provides XPath-based access to a parsed XML request body. Requires `URLENCODED_ERROR` to be 0 and Content-Type to be XML.",
	},
	{
		Name:        "ENV",
		Summary:     "Server environment variables",
		Syntax:      "ENV[:var-name]",
		Example:     `SecRule ENV:HTTPS "@streq on" "id:121,phase:1,pass"`,
		Description: "**ENV** provides access to server-side environment variables.",
	},
	// Request Path & Full Request
	{
		Name:        "ARGS_PATH",
		Summary:     "URL path-segment parameters (REST-style path variables)",
		Syntax:      "ARGS_PATH[:key]",
		Example:     `SecRule ARGS_PATH:id "@rx [^0-9]" "id:130,phase:1,deny"`,
		Description: "**ARGS_PATH** contains parameters extracted from URL path segments, used in REST APIs where values appear in the path (e.g. `/api/users/{id}`). Use `:key` to access a specific segment.",
	},
	{
		Name:        "FULL_REQUEST",
		Summary:     "Complete raw HTTP request including headers and body",
		Syntax:      "FULL_REQUEST",
		Example:     `SecRule FULL_REQUEST "@rx (?i)union.*select" "id:131,phase:2,deny"`,
		Description: "**FULL_REQUEST** contains the entire HTTP request as a single string, including the request line, all headers, and the body. Useful as a last-resort inspection target but expensive to match against.",
	},
	{
		Name:        "FULL_REQUEST_LENGTH",
		Summary:     "Total byte length of the complete HTTP request",
		Syntax:      "FULL_REQUEST_LENGTH",
		Example:     `SecRule FULL_REQUEST_LENGTH "@gt 1048576" "id:132,phase:1,deny"`,
		Description: "**FULL_REQUEST_LENGTH** contains the total size in bytes of the entire request (headers + body combined).",
	},
	{
		Name:        "PATH_INFO",
		Summary:     "Extra path information from the URI (CGI PATH_INFO)",
		Syntax:      "PATH_INFO",
		Example:     `SecRule PATH_INFO "@rx \\.php$" "id:133,phase:1,deny"`,
		Description: "**PATH_INFO** contains the extra path information appended to the script name in CGI-style URIs (e.g. for `/cgi-bin/script.cgi/extra/path`, PATH_INFO is `/extra/path`).",
	},
	// Parsed Body Collections
	{
		Name:        "JSON",
		Summary:     "Parsed JSON request body — access fields via path notation",
		Syntax:      "JSON[/path/to/field]",
		Example:     `SecRule JSON[/user/name] "@rx admin" "id:140,phase:2,deny"`,
		Description: "**JSON** provides access to parsed JSON request body fields using JSON Pointer notation.\nRequires `SecRequestBodyAccess On` and a `Content-Type: application/json` request.\n\nUse `/field` for top-level keys and `/nested/key` for nested objects.",
	},
	{
		Name:        "REQUEST_XML",
		Summary:     "XPath access to the parsed XML request body",
		Syntax:      "REQUEST_XML[xpath-expression]",
		Example:     `SecRule REQUEST_XML[//*/@src] "@rx javascript:" "id:141,phase:2,deny"`,
		Description: "**REQUEST_XML** is equivalent to `XML` — it provides XPath-based access to a parsed XML request body.\nRequires `SecRequestBodyAccess On` and an XML `Content-Type`.",
	},
	{
		Name:        "RESPONSE_XML",
		Summary:     "XPath access to the parsed XML response body",
		Syntax:      "RESPONSE_XML[xpath-expression]",
		Example:     `SecRule RESPONSE_XML[//error/code] "@rx 5[0-9]{2}" "id:142,phase:4,deny"`,
		Description: "**RESPONSE_XML** provides XPath-based access to the parsed XML response body.\nRequires `SecResponseBodyAccess On` and an XML `Content-Type`.",
	},
	{
		Name:        "RESPONSE_ARGS",
		Summary:     "Parameters parsed from a URL-encoded response body",
		Syntax:      "RESPONSE_ARGS[:key]",
		Example:     `SecRule RESPONSE_ARGS:error "@rx sensitive" "id:143,phase:4,deny"`,
		Description: "**RESPONSE_ARGS** contains parameters parsed from a `application/x-www-form-urlencoded` response body.\nRequires `SecResponseBodyAccess On`.",
	},
	// Request Body Processor Errors
	{
		Name:        "REQBODY_PROCESSOR_ERROR",
		Summary:     "Non-zero when the request body processor itself encountered an error",
		Syntax:      "REQBODY_PROCESSOR_ERROR",
		Example:     `SecRule REQBODY_PROCESSOR_ERROR "!@eq 0" "id:150,phase:2,deny,msg:'Request body processor error'"`,
		Description: "**REQBODY_PROCESSOR_ERROR** is set to a non-zero value when the request body processor (e.g. JSON or XML parser) encounters an internal error, distinct from a parse validation failure (`REQBODY_ERROR`).",
	},
	{
		Name:        "REQBODY_PROCESSOR_ERROR_MSG",
		Summary:     "Error message from the request body processor",
		Syntax:      "REQBODY_PROCESSOR_ERROR_MSG",
		Example:     `SecRule REQBODY_PROCESSOR_ERROR "!@eq 0" "id:151,phase:2,deny,logdata:'%{REQBODY_PROCESSOR_ERROR_MSG}'"`,
		Description: "**REQBODY_PROCESSOR_ERROR_MSG** contains the human-readable internal error message when `REQBODY_PROCESSOR_ERROR` is non-zero.",
	},
	// Response Body Processing
	{
		Name:        "RES_BODY_PROCESSOR",
		Summary:     "Active response body processor type",
		Syntax:      "RES_BODY_PROCESSOR",
		Example:     `SecRule RES_BODY_PROCESSOR "@streq JSON" "id:155,phase:4,pass,log"`,
		Description: "**RES_BODY_PROCESSOR** indicates which processor was used to parse the response body: `URLENCODED`, `JSON`, `XML`, or empty if none.",
	},
	{
		Name:        "RES_BODY_ERROR",
		Summary:     "Non-zero when response body parsing failed",
		Syntax:      "RES_BODY_ERROR",
		Example:     `SecRule RES_BODY_ERROR "!@eq 0" "id:156,phase:4,deny,msg:'Response body parse error'"`,
		Description: "**RES_BODY_ERROR** is set to a non-zero value when the response body processor encounters a parse error.",
	},
	{
		Name:        "RES_BODY_ERROR_MSG",
		Summary:     "Error message from the response body parser",
		Syntax:      "RES_BODY_ERROR_MSG",
		Example:     `SecRule RES_BODY_ERROR "!@eq 0" "id:157,phase:4,deny,logdata:'%{RES_BODY_ERROR_MSG}'"`,
		Description: "**RES_BODY_ERROR_MSG** contains the human-readable error message when `RES_BODY_ERROR` is non-zero.",
	},
	{
		Name:        "RES_BODY_PROCESSOR_ERROR",
		Summary:     "Non-zero when the response body processor itself encountered an error",
		Syntax:      "RES_BODY_PROCESSOR_ERROR",
		Example:     `SecRule RES_BODY_PROCESSOR_ERROR "!@eq 0" "id:158,phase:4,deny"`,
		Description: "**RES_BODY_PROCESSOR_ERROR** is set when the response body processor encounters an internal error distinct from a validation failure.",
	},
	{
		Name:        "RES_BODY_PROCESSOR_ERROR_MSG",
		Summary:     "Error message from the response body processor",
		Syntax:      "RES_BODY_PROCESSOR_ERROR_MSG",
		Example:     `SecRule RES_BODY_PROCESSOR_ERROR "!@eq 0" "id:159,phase:4,deny,logdata:'%{RES_BODY_PROCESSOR_ERROR_MSG}'"`,
		Description: "**RES_BODY_PROCESSOR_ERROR_MSG** contains the human-readable error message when `RES_BODY_PROCESSOR_ERROR` is non-zero.",
	},
	// Multipart Extended Variables
	{
		Name:        "MULTIPART_FILENAME",
		Summary:     "Filename values from multipart upload parts",
		Syntax:      "MULTIPART_FILENAME[:field]",
		Example:     `SecRule MULTIPART_FILENAME "@rx \.php$" "id:160,phase:2,deny"`,
		Description: "**MULTIPART_FILENAME** is a collection of the `filename` attribute values from multipart `Content-Disposition` headers. Use `:field` to access the filename for a specific form field.",
	},
	{
		Name:        "MULTIPART_NAME",
		Summary:     "Form field names from multipart upload parts",
		Syntax:      "MULTIPART_NAME[:index]",
		Example:     `SecRule MULTIPART_NAME "@rx ^__proto__$" "id:161,phase:2,deny"`,
		Description: "**MULTIPART_NAME** contains the `name` attribute values from multipart `Content-Disposition` headers.",
	},
	{
		Name:        "MULTIPART_PART_HEADERS",
		Summary:     "Individual MIME headers for each multipart part",
		Syntax:      "MULTIPART_PART_HEADERS[:field]",
		Example:     `SecRule MULTIPART_PART_HEADERS "@rx Content-Type:.*php" "id:162,phase:2,deny"`,
		Description: "**MULTIPART_PART_HEADERS** contains the raw MIME headers for each individual part in a multipart request body.",
	},
	{
		Name:        "MULTIPART_DATA_BEFORE",
		Summary:     "Data appearing before the first multipart boundary",
		Syntax:      "MULTIPART_DATA_BEFORE",
		Example:     `SecRule MULTIPART_DATA_BEFORE "!@eq 0" "id:163,phase:2,deny,msg:'Data before multipart boundary'"`,
		Description: "**MULTIPART_DATA_BEFORE** is set when there is data in the request body before the first multipart boundary, which is not allowed by the RFC and may indicate an evasion attempt.",
	},
	{
		Name:        "MULTIPART_DATA_AFTER",
		Summary:     "Data appearing after the last multipart boundary",
		Syntax:      "MULTIPART_DATA_AFTER",
		Example:     `SecRule MULTIPART_DATA_AFTER "!@eq 0" "id:164,phase:2,deny,msg:'Data after multipart boundary'"`,
		Description: "**MULTIPART_DATA_AFTER** is set when there is data in the request body after the final multipart boundary, which may indicate an evasion attempt.",
	},
	{
		Name:        "MULTIPART_FILE_LIMIT_EXCEEDED",
		Summary:     "Set when the number of uploaded files exceeds SecUploadFileLimit",
		Syntax:      "MULTIPART_FILE_LIMIT_EXCEEDED",
		Example:     `SecRule MULTIPART_FILE_LIMIT_EXCEEDED "!@eq 0" "id:165,phase:2,deny"`,
		Description: "**MULTIPART_FILE_LIMIT_EXCEEDED** is set to non-zero when the number of uploaded files in a multipart request exceeds `SecUploadFileLimit`.",
	},
	{
		Name:        "MULTIPART_BOUNDARY_QUOTED",
		Summary:     "Set when the multipart boundary value is quoted",
		Syntax:      "MULTIPART_BOUNDARY_QUOTED",
		Example:     `SecRule MULTIPART_BOUNDARY_QUOTED "!@eq 0" "id:166,phase:2,pass,log"`,
		Description: "**MULTIPART_BOUNDARY_QUOTED** is set when the multipart boundary is enclosed in quotes in the `Content-Type` header.",
	},
	{
		Name:        "MULTIPART_BOUNDARY_WHITESPACE",
		Summary:     "Set when there is whitespace around the multipart boundary value",
		Syntax:      "MULTIPART_BOUNDARY_WHITESPACE",
		Example:     `SecRule MULTIPART_BOUNDARY_WHITESPACE "!@eq 0" "id:167,phase:2,deny"`,
		Description: "**MULTIPART_BOUNDARY_WHITESPACE** is set when the multipart boundary in the `Content-Type` header is surrounded by whitespace, which may indicate malformed or evasive requests.",
	},
	{
		Name:        "MULTIPART_CRLF_LF_LINES",
		Summary:     "Set when a multipart body mixes CRLF and LF line endings",
		Syntax:      "MULTIPART_CRLF_LF_LINES",
		Example:     `SecRule MULTIPART_CRLF_LF_LINES "!@eq 0" "id:168,phase:2,deny"`,
		Description: "**MULTIPART_CRLF_LF_LINES** is set when a multipart body contains a mix of CRLF (`\\r\\n`) and bare LF (`\\n`) line endings, which violates RFC 2046 and may be used for evasion.",
	},
	{
		Name:        "MULTIPART_HEADER_FOLDING",
		Summary:     "Set when a multipart part header contains obsolete folding",
		Syntax:      "MULTIPART_HEADER_FOLDING",
		Example:     `SecRule MULTIPART_HEADER_FOLDING "!@eq 0" "id:169,phase:2,deny"`,
		Description: "**MULTIPART_HEADER_FOLDING** is set when a part header uses obsolete header folding (a line that starts with whitespace is a continuation of the previous line).",
	},
	{
		Name:        "MULTIPART_INVALID_HEADER_FOLDING",
		Summary:     "Set when multipart header folding is syntactically invalid",
		Syntax:      "MULTIPART_INVALID_HEADER_FOLDING",
		Example:     `SecRule MULTIPART_INVALID_HEADER_FOLDING "!@eq 0" "id:170,phase:2,deny"`,
		Description: "**MULTIPART_INVALID_HEADER_FOLDING** is set when header folding is present but syntactically incorrect per RFC 2822.",
	},
	{
		Name:        "MULTIPART_INVALID_PART",
		Summary:     "Set when a malformed multipart part is detected",
		Syntax:      "MULTIPART_INVALID_PART",
		Example:     `SecRule MULTIPART_INVALID_PART "!@eq 0" "id:171,phase:2,deny"`,
		Description: "**MULTIPART_INVALID_PART** is set when the multipart parser encounters a part that does not conform to the RFC, such as missing headers.",
	},
	{
		Name:        "MULTIPART_INVALID_QUOTING",
		Summary:     "Set when the multipart boundary quoting is invalid",
		Syntax:      "MULTIPART_INVALID_QUOTING",
		Example:     `SecRule MULTIPART_INVALID_QUOTING "!@eq 0" "id:172,phase:2,deny"`,
		Description: "**MULTIPART_INVALID_QUOTING** is set when the boundary parameter quoting in the `Content-Type` header is syntactically invalid.",
	},
	{
		Name:        "MULTIPART_LF_LINE",
		Summary:     "Set when a multipart body line uses bare LF instead of CRLF",
		Syntax:      "MULTIPART_LF_LINE",
		Example:     `SecRule MULTIPART_LF_LINE "!@eq 0" "id:173,phase:2,deny"`,
		Description: "**MULTIPART_LF_LINE** is set when one or more lines in the multipart body are terminated with a bare LF (`\\n`) rather than CRLF (`\\r\\n`), violating RFC 2046.",
	},
	{
		Name:        "MULTIPART_MISSING_SEMICOLON",
		Summary:     "Set when the multipart Content-Type is missing the semicolon before the boundary",
		Syntax:      "MULTIPART_MISSING_SEMICOLON",
		Example:     `SecRule MULTIPART_MISSING_SEMICOLON "!@eq 0" "id:174,phase:2,deny"`,
		Description: "**MULTIPART_MISSING_SEMICOLON** is set when the `Content-Type` header is missing the semicolon that should separate the MIME type from the `boundary=` parameter.",
	},
	// Transaction Metadata
	{
		Name:        "UNIQUE_ID",
		Summary:     "Unique identifier for this transaction",
		Syntax:      "UNIQUE_ID",
		Example:     `SecAction "id:180,phase:1,pass,setvar:TX.id=%{UNIQUE_ID}"`,
		Description: "**UNIQUE_ID** contains a unique string that identifies the current transaction. It can be used to correlate WAF log entries with application logs.",
	},
	{
		Name:        "URLENCODED_ERROR",
		Summary:     "Set when URL-encoded request body parsing fails",
		Syntax:      "URLENCODED_ERROR",
		Example:     `SecRule URLENCODED_ERROR "!@eq 0" "id:181,phase:2,deny,msg:'Invalid URL encoding'"`,
		Description: "**URLENCODED_ERROR** is set to a non-zero value when the URL-encoded request body contains invalid percent-encoded sequences.",
	},
	{
		Name:        "RULE",
		Summary:     "Metadata about the currently executing rule",
		Syntax:      "RULE[:field]",
		Example:     `SecAction "id:182,phase:1,pass,logdata:'Rule ID: %{RULE.id}'"`,
		Description: "**RULE** is a collection containing metadata about the currently executing rule:\n- `RULE.id` — the rule's numeric ID\n- `RULE.rev` — the revision\n- `RULE.severity` — the severity\n- `RULE.msg` — the message\n- `RULE.logdata` — the log data",
	},
	// Session & User Identity
	{
		Name:        "SESSIONID",
		Summary:     "Session identifier string set by the setsid action",
		Syntax:      "SESSIONID",
		Example:     `SecRule SESSIONID "@rx ^[a-f0-9]{32}$" "id:185,phase:1,pass"`,
		Description: "**SESSIONID** contains the session identifier set via the `setsid` action. Used to key the `SESSION` persistent collection.",
	},
	{
		Name:        "USERID",
		Summary:     "User identifier string set by the setuid action",
		Syntax:      "USERID",
		Example:     `SecAction "id:186,phase:1,pass,setuid:%{REQUEST_COOKIES:username}"`,
		Description: "**USERID** contains the user identifier set via the `setuid` action. Used for user-based persistent tracking.",
	},
	// Fine-grained Time Variables
	{
		Name:        "TIME_DAY",
		Summary:     "Current day of the month (1–31)",
		Syntax:      "TIME_DAY",
		Example:     `SecRule TIME_DAY "@eq 1" "id:190,phase:1,pass,log,msg:'First of the month'"`,
		Description: "**TIME_DAY** contains the current day of the month as a decimal integer (1–31).",
	},
	{
		Name:        "TIME_HOUR",
		Summary:     "Current hour of the day (0–23)",
		Syntax:      "TIME_HOUR",
		Example:     `SecRule TIME_HOUR "@lt 8" "id:191,phase:1,deny,msg:'Outside business hours'"`,
		Description: "**TIME_HOUR** contains the current hour of the day in 24-hour notation (0–23).",
	},
	{
		Name:        "TIME_MIN",
		Summary:     "Current minute (0–59)",
		Syntax:      "TIME_MIN",
		Example:     `SecRule TIME_MIN "@lt 30" "id:192,phase:1,pass,log"`,
		Description: "**TIME_MIN** contains the current minute of the hour (0–59).",
	},
	{
		Name:        "TIME_MON",
		Summary:     "Current month (0=January, 11=December)",
		Syntax:      "TIME_MON",
		Example:     `SecRule TIME_MON "@eq 0" "id:193,phase:1,pass,log,msg:'January access'"`,
		Description: "**TIME_MON** contains the current month as a decimal integer where 0=January and 11=December.",
	},
	{
		Name:        "TIME_SEC",
		Summary:     "Current second (0–59)",
		Syntax:      "TIME_SEC",
		Example:     `SecRule TIME_SEC "@lt 30" "id:194,phase:1,pass"`,
		Description: "**TIME_SEC** contains the current second of the minute (0–59).",
	},
	{
		Name:        "TIME_WDAY",
		Summary:     "Current day of the week (0=Sunday, 6=Saturday)",
		Syntax:      "TIME_WDAY",
		Example:     `SecRule TIME_WDAY "@within 6 0" "id:195,phase:1,deny,msg:'Weekend access blocked'"`,
		Description: "**TIME_WDAY** contains the current day of the week where 0=Sunday and 6=Saturday.",
	},
	{
		Name:        "TIME_YEAR",
		Summary:     "Current four-digit year",
		Syntax:      "TIME_YEAR",
		Example:     `SecRule TIME_YEAR "@lt 2025" "id:196,phase:1,deny,msg:'System clock error'"`,
		Description: "**TIME_YEAR** contains the current year as a four-digit decimal integer.",
	},
}
